server:
  port: ${PORT:8888}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@mland-discovery-server:8761/eureka

spring:
  application:
    name: mland-config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          basedir: git_config
          default-label: main
          uri: https://github.com/0ffffh/mland_config.git

