server:
  port: ${PORT:8888}

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka:eureka@localhost:8761/eureka

spring:
  application:
    name: mland-config-server

  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config # Config files for all microservices
            - classpath:/config/{application} # Config files for specific applications


