---
version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mland

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgresdb

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"


  mland-config-server:
    image: 0ffffh/mland-config-server:latest
    container_name: mland-config-server
    depends_on:
      - postgresdb
      - broker
      - zipkin
    restart: always


  mland-discovery-server:
    image: 0ffffh/mland-discovery-server:latest
    container_name: mland-discovery-server
    environment:
      CONFIG_SERVER_URL: http://mland-config-server:8888
      JAVA_OPTS: -Dspring.profiles.active=docker
    depends_on:
      - mland-config-server
    restart: always


  mland-oauth2-server:
    image: 0ffffh/mland-oauth2-server:latest
    container_name: mland-oauth2-server
    environment:
      CONFIG_SERVER_URL: http://mland-config-server:8888
      JAVA_OPTS: -Dspring.profiles.active=docker
    ports:
      - "9000:9000"
    depends_on:
      - mland-config-server
      - mland-discovery-server
    restart: always


  mland-api-gateway:
    image: 0ffffh/mland-api-gateway:latest
    container_name: mland-api-gateway
    environment:
      CONFIG_SERVER_URL: http://mland-config-server:8888
      JAVA_OPTS: -Dspring.profiles.active=docker
    ports:
      - "8080:8080"
    depends_on:
      - mland-oauth2-server
    restart: always


  mland-mail-sender:
    image: 0ffffh/mland-mail-sender:latest
    container_name: mland-mail-sender
    environment:
      CONFIG_SERVER_URL: http://mland-config-server:8888
      JAVA_OPTS: -Dspring.profiles.active=docker
    depends_on:
      - mland-api-gateway
    restart: always


  mland-currency-service:
    image: 0ffffh/mland-currency-service:latest
    container_name: mland-currency-service
    environment:
      CONFIG_SERVER_URL: http://mland-config-server:8888
      JAVA_OPTS: -Dspring.profiles.active=docker
    depends_on:
      - mland-api-gateway
    restart: always


  mland-resource-server:
    image: 0ffffh/mland-resource-server:latest
    container_name: mland-resource-server
    environment:
      CONFIG_SERVER_URL: http://mland-config-server:8888
      JAVA_OPTS: -Dspring.profiles.active=docker
    depends_on:
      - mland-api-gateway
    restart: always


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - mland-config-server
      - mland-discovery-server
      - mland-api-gateway
      - mland-oauth2-server
      - mland-mail-sender
      - mland-currency-service
      - mland-resource-server

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin