global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: eureka-discovery
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://mland-discovery-server:8761/eureka
        basic_auth:
          username: eureka
          password: eureka
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance


