
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_PORT
              value: "80"
          image: dpage/pgadmin
          imagePullPolicy: IfNotPresent
          name: pgadmin
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 4096Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
spec:
  ports:
    - name: padmin-port
      nodePort: 30300
      port: 80
      targetPort: 80
  selector:
    app: pgadmin
  type: NodePort